# Generated by Django 3.0.6 on 2020-05-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Encrypted_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_message', models.CharField(max_length=500)),
                ('public_key', models.CharField(max_length=5000)),
                ('private_key', models.CharField(max_length=5000)),
                ('encrypted_file', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encryption.User')),
            ],
        ),
    ]
