# Generated by Django 3.0.6 on 2020-05-11 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0002_user_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypted_data',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
