# Generated by Django 3.0.6 on 2020-05-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0003_encrypted_data_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypted_data',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
